name: taxisnet_afm
description: Get AFM details from TAXISnet
version: 1.0.1
repository: https://github.com/johnstef99/taxisnet-afm

environment:
  sdk: ^3.1.1

dependencies:
  http: ">=1.0.0 <=2.0.0"
  xml: ">=5.0.0 <=7.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
